config/routes.rb
FirstProject::Application.routes.draw do

  root "home#index"
  get "home/projects"
  get "home/about"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def projects
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_nav.html.erb
<div class="nav">
  <ul>
    <li><%= link_to "Austin Shymanski", root_path %></li>
    <li><%= link_to "Projects", home_projects_path %></li>
    <li><%= link_to "About Me", home_about_path %></li>
</div>

app/views/home/about.html.erb
<%= render 'nav' %>

<div id="left_bar">
  <h2>Early Life</h2>
  <p>I have always been in love with technology. As soon as I was able to sit on the computer chair and reach the mouse I was doing something with the computer. I remember playing Commander Keen which was on an 8 inch floppy disk. As I grew older my love for technology grew as well. I built my first desktop when I was 13 with no hardware experience, but wanted to do it so bad I just ordered all the parts I thought I would need and started putting pieces together like Legos.</p>
</div>

<div id="center_bar">
  <h2>Teenage Years</h2>
  <p></p>
</div>

<div id="right_bar">
  <h2>Current Life</h2>
  <p></p>
</div>

app/views/home/index.html.erb
<%= render 'nav' %>

app/views/home/projects.html.erb
<%= render 'nav' %>
<h1>Hey</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>